<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pe_pagephpcontentelement"
 *
 * Auto generated by Extension Builder 2015-10-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Page PHP Content Element',
	'description' => 'This extension allows you to add php scripts via frontend plugin.',
	'category' => 'plugin',
	'author' => 'Danny Faak',
	'author_email' => 'hello@public-enrage.me',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.5.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
